# Outline

In [4]:
import sys
import os

# add utils to path for experimental subfolder
sys.path.append("/net/talisker/home/benos/mae117/collaborations/ATAConv")

## Look over entirety of the code

## I need to test the one-hot encoding in utils.py

In [21]:
from typing_extensions import runtime
import utils
import time

string="ATCACGATCGATATACG"

start_time = time.time()
string_1he=utils.returnonehot(string)
run_time = start_time - time.time()

print("this took: ", run_time)

this took:  -0.00027561187744140625


In [13]:
len(string)
string_1he.shape
print(string_1he)

[[1. 0. 0. 1. 0. 0. 1. 0. 0. 0. 1. 0. 1. 0. 1. 0. 0.]
 [0. 0. 1. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 1. 0. 0. 0.]]


In [18]:
import warnings
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
import re

class Sequence:
    def __init__(self) -> None:
        pass



def get_onehot(string):
    try:
        print(string)
    except:
        raise Exception("You input an invalid string.")

if __name__=="__main__":
    get_onehot(string)

ATCACGATCGATATACG


## Look for more pertient ways to create a standard test/train split in the data
- This is available on klaus

## Look for a standard way to read motif formats in R or python